apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: homelab-infra
spec:
  topology:
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: proxmox-worker
          replicas: 1
        - class: proxmox-loadbalancer
          replicas: 0
    variables:
      - name: controlPlaneEndpoint
        value:
          host: 10.10.10.10
          port: 6443
      - name: ipv4Config
        value:
          addresses: [10.10.10.20-10.10.10.30]
      - name: cloneSpec
        value:
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINo+Mazsj4x9O5mGKLVwic8zUWmg/gihsEK3ZLZ7yt3f nils@nixos
