---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/proxmox-cluster-cni: cilium
  name: homelab-infra
spec:
  topology:
    class: proxmox-clusterclass-cilium-v0.1.0
    version: v1.29.0
    controlPlane:
      replicas: 0
    workers:
      machineDeployments:
        - class: proxmox-worker
          name: proxmox-worker-pool
          replicas: 0
        - class: proxmox-loadbalancer
          name: proxmox-loadbalancer-pool
          replicas: 0
    variables:
      - name: allowedNodes
        value:
          - pve1
      - name: controlPlaneEndpoint
        value:
          host: 192.168.2.100
          port: 6443
      - name: dnsServers
        value: [192.168.2.1]
      - name: ipv4Config
        value:
          addresses: [192.168.2.101-192.168.2.120]
          gateway: 192.168.2.1
          prefix: 24
      - name: kubeProxy
        value:
          mode: iptables
      - name: cloneSpec
        value:
          machineSpec:
            controlPlane:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 100
              numSockets: 1
              numCores: 4
              memoryMiB: 4096
            workerNode:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 100
              numSockets: 1
              numCores: 4
              memoryMiB: 4096
            loadBalancer:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 100
              numSockets: 1
              numCores: 4
              memoryMiB: 4096
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINo+Mazsj4x9O5mGKLVwic8zUWmg/gihsEK3ZLZ7yt3f nils@nixos
