---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  labels:
    cluster.x-k8s.io/proxmox-cluster-cni: cilium
  name: homelab-infra
spec:
  topology:
    class: proxmox-clusterclass-cilium-v0.1.0
    version: 1.29.0
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: proxmox-worker
          name: proxmox-worker-pool
          replicas: 1
        - class: proxmox-loadbalancer
          name: proxmox-loadbalancer-pool
          replicas: 0
    variables:
      - name: allowedNodes
        value:
          - pve1
      - name: controlPlaneEndpoint
        value:
          host: 10.10.10.10
          port: 6443
      - name: dnsServers
        value: [8.8.8.8, 8.8.4.4]
      - name: ipv4Config
        value:
          addresses: [10.10.10.20-10.10.10.30]
          gateway: 10.10.10.1
          prefix: 24
      - name: kubeProxy
        value:
          mode: iptables
      - name: cloneSpec
        value:
          machineSpec:
            controlPlane:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
            workerNode:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
            loadBalancer:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINo+Mazsj4x9O5mGKLVwic8zUWmg/gihsEK3ZLZ7yt3f nils@nixos
