---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
spec:
  topology:
    workers:
    variables:
      - name: allowedNodes
        value:
          - pve1
      - name: dnsServers
        value: [8.8.8.8, 8.8.4.4]
      - name: kubeProxy
        value:
          mode: iptables
      - name: cloneSpec
        value:
          machineSpec:
            controlPlane:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
            workerNode:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
            loadBalancer:
              network:
                default:
                  bridge: vmbr0
              sourceNode: pve1
              templateID: 101
          sshAuthorizedKeys:
            - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINo+Mazsj4x9O5mGKLVwic8zUWmg/gihsEK3ZLZ7yt3f nils@nixos
